---
title: "CCL8-AND-CCL13_GSEA"
author: "Kelvin Mo"
date: "2024-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(BiocManager)
BiocManager::install("clusterProfiler")
BiocManager::install("pathview")
BiocManager::install("enrichplot")
library(clusterProfiler)
library(enrichplot)
# we use ggplot2 to add x axis labels (ex: ridgeplot)
library(ggplot2)
```

```{r}
# Human annotation
organism = "org.Hs.eg.db"
BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
```

## FNA
```{r}
# reading in data from deseq2
df = read.csv("DGE/fna/CCL8-OR-CCL13-SCT-DE_genes.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list <- df$avg_log2FC

# name the vector
names(original_gene_list) <- df$X

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)

head(gene_list)
keytypes(org.Hs.eg.db)

head(df)
```


```{r}
# SYMBOL 2
# ALIAS 3
gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             minGSSize = 3, 
             maxGSSize = 500, 
             pvalueCutoff = 0.05, 
             nPermSimple = 1000,
             verbose = TRUE, 
             OrgDb = organism) 
             #pAdjustMethod = "hochberg")
```

```{r}
require(DOSE)
dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)
ggsave("../CCL8-OR-CCL13_FNA_GSEA-pathway-top10.eps", width = 7, height = 5)
```

## Enrichment Map
```{r}
# categorySize can be either 'pvalue' or 'geneNum'
cnetplot(gse, categorySize="pvalue", foldChange=gene_list, showCategory = 3)
ggsave("../CCL8-OR-CCL13_FNA_GSEA-netplot.png", width = 7, height = 5)
```
## Ridgeplot
```{r}
ridgeplot(gse) + labs(x = "enrichment distribution")
ggsave("../CCL8-OR-CCL13_FNA_GSEA-pathway-top10-ridgeplot.eps", width = 7, height = 7)
```







## EcoTyper
```{r}
# reading in data from deseq2
df = read.csv("DGE/ecotyper/CCL8-OR-CCL13-SCT-DE_genes.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list <- df$avg_log2FC

# name the vector
names(original_gene_list) <- df$X

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)

head(gene_list)
keytypes(org.Hs.eg.db)

head(df)
```


```{r}
# SYMBOL 2
# ALIAS 3
gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             minGSSize = 3, 
             maxGSSize = 500, 
             pvalueCutoff = 0.05, 
             nPermSimple = 1000,
             verbose = TRUE, 
             OrgDb = organism) 
             #pAdjustMethod = "hochberg")
```

```{r}
require(DOSE)
dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)
ggsave("../CCL8-OR-CCL13_EcoTyper_GSEA-pathway-top10.eps", width = 7, height = 5)
```

## Enrichment Map
```{r}
# categorySize can be either 'pvalue' or 'geneNum'
cnetplot(gse, categorySize="pvalue", foldChange=gene_list, showCategory = 3)
ggsave("../CCL8-OR-CCL13_EcoTyper_GSEA-netplot.png", width = 7, height = 5)
```
## Ridgeplot
```{r}
ridgeplot(gse) + labs(x = "enrichment distribution")
ggsave("../CCL8-OR-CCL13_EcoTyper_GSEA-pathway-top10-ridgeplot.eps", width = 7, height = 5)
```



